### ISSUE TITLE
Emacs interface(a la epg)?

### ISSUE THREAD

**Issue by samrat** [skeeto/enchive#11]
It would be really useful if I could open up an encrypted file in Emacs, upon which I'd be prompted for a password. Then, when I'm done editing the file, the emacs interface would encrypt the file and close the buffer.

**Comment by nico202** [comment]
https://github.com/skeeto/enchive/blob/master/enchive-mode.el

**Comment by skeeto** [comment]
Thanks, @nico202. The new --pinentry feature in Enchive 3.4 makes this 
work more smoothly, too.

**Comment by samrat** [comment]
Thanks, didn't notice the file in the repo. However, I'm getting this error when trying to open a `.enchive` file with `enchive-mode` enabled: `if: Enchive subprocess failed`. I've tried setting `enchive-program-name` to the absolute path of the enchive binary. (By the way, is it intentional that the variable isn't used anywhere else?)

**Comment by skeeto** [comment]
Oops, that was a mistake. Just fixed it. If Enchive was already in your 
PATH as "enchive", then another possibility is the pinentry program 
failed to run. Are you able to use the --pinentry option standalone?

    enchive --pinentry extract <myfile.txt.enchive

Or, more directly, do you get a GUI passphrase prompt if you run this?

    echo GETPIN | pinentry

If the default is the curses or tty interfaces, this will fail, and it 
also generally won't work from within Emacs. There should be another 
Emacs option to control this. For example, on the command line you can 
choose the pinentry program:

    enchive --pinentry=pinentry-qt4 extract <myfile.txt.enchive

**Comment by samrat** [comment]
Alright, here's what I did to get this working on a Mac(macOS 10.12.5)-- install `pinentry-mac` using homebrew(the `pinentry` package doesn't seem to have the GUI prompt), then create a symbolic link so that you have a `pinentry` binary in your PATH(`ln -s /usr/local/bin/pinentry-mac ~/bin/pinentry`; `pinentry-mac` installs a binary that's called `pinentry-mac`).

I will close this issue now. Thanks!
