### ISSUE TITLE
Being added to nixpkgs

### ISSUE THREAD

**Issue by nico202** [skeeto/enchive#6]
Hi, I wanted to let you know that I'm asking for enchive to be added to the nixpkgs repository. nixpkgs is the pkg collection of the nix package manager.

You can find the pull request [here](https://github.com/NixOS/nixpkgs/pull/28713)

Thanks for this wonderful piece of software

**Comment by skeeto** [comment]
Exciting news, thanks! I've heard of Nix but haven't gotten around to 
checking it out yet. I'll have to increase the priority on that.

**Comment by nico202** [comment]
merged, closing this!
As a side-note, yes, you should really try it, I'm using it on 3 machines (where I had elementaryOS, arch, and ubuntu) and I'm happy with it :)
