### ISSUE TITLE
enchive won't compress big files

### ISSUE THREAD

**Issue by nico202** [skeeto/enchive#7]
Hi, I have a 3.5Gb video file.
> enchive archive BigFile.mp4

enchive: could not open input file -- BigFile.mp4

I have not tried with other files that big, but sure up to 600Mb works. I don't think there are problems in accessing the file since I was able to check the sha1 hash. There is enough hard disk space and there not exist a file named BigFile.mp4.enchive. The only doubt I have is if it's limited by the RAM, but I have 13Gb swap so in theory it should work anyway

**Comment by skeeto** [comment]
Enchive only uses fopen(), fread(), and fwrite(), only uses fixed-size 
I/O buffers, doesn't seek, and doesn't track the total number of bytes 
anywhere, so there are absolutely no limitations on input or output 
sizes other than the limitations of the host platform (underlying 
filesystem, C library, etc.). Furthermore, the only way you will see 
this message is if `fopen("BigFile.mp4", "rb")` returned NULL.

Unfortunately I failed to print the value of errno in this case, so we 
can't see the actual cause of the error. I just pushed a commit that 
does print a more informative error message. I'd be interested in seeing 
this error message, especially if it's not something obvious (file 
doesn't exist, bad file permissions).

What operating system are you using and what compiler? (This smells a 
bit like MinGW to me.)

**Comment by nico202** [comment]
It's debian arm (raspberry pi)

enchive: could not open input file 'BigFile.mp4' -- Value too large for defined data type

**Comment by skeeto** [comment]
Ah, this makes sense now. Outside of documenting how to deal with this 
issue, I'm not really willing to adapt Enchive to annoying old flaws in 
glibc. You have two options here:

* Compile Enchive with large file support:

    make CFLAGS='-O3 -D_FILE_OFFSET_BITS=64'

* Have the shell open large files for Enchive, since presumably your 
shell has been compiled with large file support (per above):

    enchive archive <BigFile.mp4 >BigFile.mp4.enchive

IMHO, a C library should _never_ treat large files differently with 
fopen(). The failure should occur when calling ftell() or fseek().

**Comment by nico202** [comment]
Thanks
Went with the first option and it worked.
I think adding this to the docs should suffice, or changing the makefile if possibile

Thanks again, closing

**Comment by skeeto** [comment]
Thanks for taking the time to report this issue! If nothing else, 
Enchive's error messages are a little better than before.
