### ISSUE TITLE
feature: AES NI

### ISSUE THREAD

**Issue by kewlfft** [skeeto/enchive#8]
My idea was to develop [kewlfft/dse](https://github.com/kewlfft/dse) to bring some new features and I found your project. I may rather fork this one then because you have already done a very good job. 
The only thing maybe is that it is not natural to me to call _archive_ and _extract_, ciphering and deciphering in the command line but I will probably get used to it.

One improvement I had in mind for my project was to add AES NI to improve speed, is it something you have ever considered for yours or are you fully satisfied with ChaCha20?

**Comment by skeeto** [comment]
I'm satisfied with ChaCha20. The primary motivation for choosing a 
stream cipher was to avoid block padding stuff. If I did want a block 
cipher I would have chosen AES, so we're on the same wavelength.

However, even if Enchive used AES, portability and simplicity are both 
more important than performance for this tool. If, decades from now, 
someone wants to access an old encrypted archive and has its key, it 
should be very easy for them to build Enchive. They just need an ANSI C 
compiler and an OS interface that resembles either POSIX or Win32. While 
AES-NI support would be *cool*, it would add complication for very 
little gain.

**Comment by kewlfft** [comment]
Thanks for the feedback, your choices make sense. The AES-NI was indeed to make it cool and optimized for my CPU. I looked at it again for my project and this would be a lot of adaptation work and testing for limited use, especially if I am going to use your tool instead which has everything else I wanted to implement.
